spring:
    profiles:
      active: dev
server:
  port: 8011

management:
  health:
    defaults:
      enabled: false
  security:
    enabled: false

---

spring:
    profiles: dev

name: test-YAML
environment: dev
catalog-searcher:
  service:
    itunes-service:
      base-url: https://itunes.apple.com/search
    google-service:
      base-url: https://www.googleapis.com/books/v1/volumes
  search:
    param:
      max-result-size: 5
hystrix:
  command:
    default:
      execution:
        isolation:
          semaphore:
            maxConcurrentRequests: 100
          thread:
            timeoutInMilliseconds: 1000
            interruptOnTimeout: true
        timeout:
          enabled: true
  metrics:
    enabled: false
  stream:
    queue:
      size: 10000
  threadpool:
    default:
      coreSize: 100
      maximumSize: 110

---
spring:
    profiles: prod
name: prod-YAML
environment: production
catalog-searcher:
  service:
    itunes-service:
      base-url: https://itunes.apple.com/search
    google-service:
      base-url: https://www.googleapis.com/books/v1/volumes
  search:
    param:
      max-result-size: 10